apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-orion
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/FIWARE-Ops/marinera.git
    targetRevision: HEAD
    path: applications/mongodb/chart
    helm:
      values: |
        mongodb:
          architecture: standalone
          auth:
            enabled: true
            existingSecret: mongodb-secret
  destination:
    namespace: fiware
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      # resources that no longer exist get deleted on sync
      prune: true
      # sync will be attempted again on failure after self heal timeout (5 seconds by default)
      selfHeal: true
